# Generated by Django 4.2.4 on 2023-08-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('punch_in', models.DateTimeField(null=True)),
                ('punch_out', models.DateTimeField(null=True)),
                ('durations', models.IntegerField(null=True)),
            ],
        ),
    ]
